- name: install packages from yum
  yum: name={{ item }} state=latest
  with_items:
    - httpd

- name: create directories
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode=0{{ item.mode }} state=directory
  with_items:
    - {
        "path": "/opt/vagrant",
        "owner": "vagrant",
        "group": "vagrant",
        "mode": "755",
      }
